### ISSUE TITLE
Misconfigured URL in the ConfigApi.cs

### ISSUE THREAD

**Issue by VPKSoft** [tonykaralis/TMdbEasy#1]
There is an extra slash (/) character in the line 16 of the ConfigApi.cs file which leads to an exception: "Movie Id does not exist".

The code is as follows:
`            var content = await CallApiAsync($"{Url}configuration/?api_key={ApiKey}").ConfigureAwait(false)`

Should be corrected to:
`            var content = await CallApiAsync($"{Url}configuration?api_key={ApiKey}").ConfigureAwait(false);`

**Comment by VPKSoft** [comment]
Hi,
No PR's from me (must learn GIT first) - thanks for the great library though!

**Comment by tonykaralis** [comment]
No problem. This is fixed with commit be05d633ccb00721df806da7cd79d079406f0d99. Dont have time to test it, fingers crossed. Ill try release update on nuget by this evening. If the problem persists re-open this issue.

Glad someone has found it usefull 👍
