### ISSUE TITLE
v1 - Refactor/Upgrade

### ISSUE THREAD

**Issue by tonykaralis** [tonykaralis/TMdbEasy#13]
Looking to refresh this lib, improve developer experience and put some effort into making it play nicely with ASP.NET Core.

Roadmap:
Add support for asp.net core dependency injection
Refactor to clean SOLID standards
Address any async issues
Refactor internals
Improve developer experience
Update readme, add docs if necessary
Extend library to include more endpoints
Potentially move to v4 of TMDB
Heads up to any users that v1 will most likely include some major breaking changes

See project for details https://github.com/tonykaralis/TMdbEasy/projects/1

**Comment by tonykaralis** [comment]
Will address #9 #10 #11 #12

**Comment by tonykaralis** [comment]
@VPKSoft hope all is well, been a while. Just thought I would give you a heads up in case you are using this project, will be making some major changes to the lib over the next month or so. This will lead to breaking changes no doubt.

**Comment by VPKSoft** [comment]
Thanks for the heads up. Some times breaking changes are required to keep the code base in shape 👍
